# 🏛️ POC 19: Half-Century Institutional Zero-Leakage Walk-Forward Backtest (1978–2026)

**File**: [`research/notebooks/algo-alpha-execution/19_half_century_institutional_zero_leakage_walkforward_backtest.ipynb`](file:///c:/Users/honza/Desktop/projects/stock-analysis/research/notebooks/algo-alpha-execution/19_half_century_institutional_zero_leakage_walkforward_backtest.ipynb)  
**Scope**: Multi-decade institutional walk-forward benchmark across **nearly a half-century (48.6 Years: 1978–2026 / 12,264 daily trading sessions)** enforcing **Strict Trading-Bar Purging, $T+1$ Execution Lag, Point-in-Time Active Universes (Zero `bfill()`), and Survivorship Alpha Decomposition**.

---

### 🛡️ Institutional Zero-Leakage Protocol Enforced:
1. **Trading-Session Index Purge Embargo ($T_{\text{train}} \le \text{all\_dates}[t_{\text{idx}} - H]$)**:
   - Purged by exact trading calendar bars ($H=30, 15, 5$ sessions). Guarantees 100.0% zero overlapping forward target labels.
2. **Realistic $T+1$ Execution Lag**:
   - Signals computed at Day $T$ Market Close execute at Day $T+1$, earning returns strictly starting on Day $T+1$.
3. **Point-in-Time Active Universe (Zero `bfill()`)**:
   - Only stocks actively listed and trading on Day $T$ are eligible for selection, preventing pre-IPO distortion.
4. **Survivorship & Alpha Decomposition**:
   - Decomposes total performance into **Market Beta (S&P 500)** vs **Universe Selection Beta (Active Universe B&H)** vs **Pure Machine Learning Selection & Conviction Sizing Alpha**.

```
┌────────────────────────────────────────────────────────────────────────────────────────┐
│ HALF-CENTURY INSTITUTIONAL ZERO-LEAKAGE TIMELINE (1978–2026 / 48.6 YEARS)              │
│ 1978–1980: Initial Historical Burn-in & Feature Priming                                │
│ 1981–1989: 1980s Stagflation Recovery & 1987 Black Monday Crash                        │
│ 1990–1999: 1990s Tech Revolution & Dot-Com Mania                                      │
│ 2000–2009: Dot-Com Crash, 2008 Global Financial Crisis & Great Recession               │
│ 2010–2019: Post-Crisis Quantitative Easing Bull Run & Tech Dominance                  │
│ 2020–2026: COVID Shock, 2022 Inflation/Rate Hikes & GenAI Secular Wave                │
└────────────────────────────────────────────────────────────────────────────────────────┘
```

## 1. Setup & Environment Configuration

In [1]:
import os
import sys
import time
import pandas as pd
import numpy as np
import xgboost as xgb
import plotly.graph_objects as go
import plotly.express as px
from plotly.subplots import make_subplots
import matplotlib.pyplot as plt
import yfinance as yf
from tqdm.auto import tqdm

# Robust project root discovery
current_dir = os.path.abspath(os.getcwd())
while current_dir and not os.path.exists(os.path.join(current_dir, "src")):
    parent = os.path.dirname(current_dir)
    if parent == current_dir:
        break
    current_dir = parent

PROJECT_ROOT = current_dir
DATA_PATH = os.path.join(PROJECT_ROOT, "data", "processed", "master_panel_1975_2026.parquet")
LOCAL_DATA_DIR = os.path.join(PROJECT_ROOT, "research", "notebooks", "algo-alpha-execution", "data", "fetched")

print(f"📁 Project Root: {PROJECT_ROOT}")
print(f"📁 Loading Half-Century Master Parquet: {DATA_PATH}")

t0 = time.perf_counter()
df_master = pd.read_parquet(DATA_PATH)
df_master['date'] = pd.to_datetime(df_master['date'])

# Precompute forward prediction horizons (trading session shifts)
df_master['target_fwd_5d'] = df_master.groupby('ticker')['close'].transform(lambda s: s.shift(-5) / s - 1.0)
df_master['target_fwd_15d'] = df_master.groupby('ticker')['close'].transform(lambda s: s.shift(-15) / s - 1.0)
df_master['target_fwd_30d'] = df_master.groupby('ticker')['close'].transform(lambda s: s.shift(-30) / s - 1.0)

print(f"✅ Loaded {len(df_master):,} records across {df_master['ticker'].nunique()} tickers ({df_master['date'].min().strftime('%Y-%m-%d')} to {df_master['date'].max().strftime('%Y-%m-%d')}) in {time.perf_counter()-t0:.2f}s!")

📁 Project Root: c:\Users\honza\Desktop\projects\stock-analysis
📁 Loading Half-Century Master Parquet: c:\Users\honza\Desktop\projects\stock-analysis\data\processed\master_panel_1975_2026.parquet

✅ Loaded 638,434 records across 60 tickers (1978-01-03 to 2026-08-27) in 0.87s!

## 2. Ingest S&P 500 (`^GSPC`) Benchmark & Point-in-Time Price Matrix (No `bfill()`)

In [2]:
# Strictly NO backward filling (bfill) - only forward fill during active trading
prices_pivot = df_master.pivot(index='date', columns='ticker', values='close').ffill()
daily_rets = prices_pivot.pct_change().fillna(0.0)
daily_rets_mat = daily_rets.values
all_dates = prices_pivot.index
start_dt = all_dates[0].strftime('%Y-%m-%d')
end_dt = all_dates[-1].strftime('%Y-%m-%d')
n_days, n_tickers = daily_rets_mat.shape

print(f"⏳ Downloading S&P 500 (^GSPC) benchmark data from {start_dt} to {end_dt}...")
spx_raw = yf.download("^GSPC", start=start_dt, end=end_dt, progress=False)
if isinstance(spx_raw.columns, pd.MultiIndex):
    spx_raw.columns = spx_raw.columns.get_level_values(0)

spx_aligned = spx_raw['Close'].reindex(all_dates).ffill().bfill()
spx_equity = (spx_aligned / spx_aligned.iloc[0]) * 100.0

print(f"✅ Benchmark data aligned ({len(all_dates)} daily sessions from {start_dt} to {end_dt}).")

⏳ Downloading S&P 500 (^GSPC) benchmark data from 1978-01-03 to 2026-08-27...

✅ Benchmark data aligned (12264 daily sessions from 1978-01-03 to 2026-08-27).

## 3. Strict Trading-Days Purged Walk-Forward Simulation (1981–2026)

In [3]:
features = [
    'revenue_growth', 'net_margin', 'sentiment_score', 'rsi_14', 'macd',
    'is_opp_buy', 'is_pol_buy', 'ewma_volatility', 'daily_news_count',
    'daily_news_finbert_sentiment', 'news_volume_intensity',
    'news_decay_tau_1d_ema', 'news_decay_tau_3d_ema', 'news_sentiment_velocity'
]

burnin_end_date = pd.to_datetime('1981-01-02')

w_active_bh = np.zeros_like(daily_rets_mat)
w_purged_30_5 = np.zeros_like(daily_rets_mat)
w_purged_30_30 = np.zeros_like(daily_rets_mat)
w_purged_15_15 = np.zeros_like(daily_rets_mat)

# -----------------------------------------------------------------------------
# 1. 30-DAY REBALANCE CYCLES (1981–2026: ~370 Cycles / Strict Trading-Bar Purge + T+1 Lag)
# -----------------------------------------------------------------------------
F30 = 31
rebal_dates_30 = [d for d in all_dates[::F30] if d >= burnin_end_date]
print(f"🚀 Running Half-Century Strict Trading-Days Purged 30-Day Walk-Forward ({len(rebal_dates_30)} cycles across 45.6 years)...")

t0_loop30 = time.perf_counter()

for reb_date in tqdm(rebal_dates_30, desc="30-Day Cycles"):
    t_idx = all_dates.get_loc(reb_date)
    end_idx = min(t_idx + 1 + F30, n_days)
    
    # 1. POINT-IN-TIME ACTIVE CANDIDATES (Only stocks actively trading on Day T)
    cand_df = df_master[(df_master['date'] == reb_date) & df_master['close'].notnull()]
    active_tickers = cand_df['ticker'].tolist()
    if len(active_tickers) == 0:
        continue
        
    # Active Universe Equal-Weight Benchmark
    active_idx = [prices_pivot.columns.get_loc(s) for s in active_tickers if s in prices_pivot.columns]
    w_active_bh[t_idx+1:end_idx, active_idx] = 1.0 / len(active_idx)
    
    # 2. STRICT TRADING-SESSION PURGED TRAINING (Zero Overlap: Cutoff <= all_dates[t_idx - H])
    # A. 5-Day Model: Cutoff at least 5 trading bars prior to t_idx
    purge_idx_5 = max(0, t_idx - 5)
    train_5d = df_master[df_master['date'] <= all_dates[purge_idx_5]].tail(100000)
    train_5d_clean = train_5d[train_5d['target_fwd_5d'].notnull()]
    
    m_5d = xgb.XGBRegressor(n_estimators=40, max_depth=4, learning_rate=0.05, n_jobs=-1, random_state=42, tree_method='hist')
    m_5d.fit(train_5d_clean[features], train_5d_clean['target_fwd_5d'])
    p_5d = pd.Series(m_5d.predict(cand_df[features]), index=cand_df['ticker']).nlargest(min(50, len(cand_df))).index
    w_eq_5d = np.full(len(p_5d), 1.0 / len(p_5d))
    idx_5d = [prices_pivot.columns.get_loc(s) for s in p_5d if s in prices_pivot.columns]
    # T+1 Execution Lag
    w_purged_30_5[t_idx+1:end_idx, idx_5d] = w_eq_5d[:len(idx_5d)]
    
    # B. 30-Day Model: Cutoff at least 30 trading bars prior to t_idx
    purge_idx_30 = max(0, t_idx - 30)
    train_30d = df_master[df_master['date'] <= all_dates[purge_idx_30]].tail(100000)
    train_30d_clean = train_30d[train_30d['target_fwd_30d'].notnull()]
    
    m_30d = xgb.XGBRegressor(n_estimators=40, max_depth=4, learning_rate=0.05, n_jobs=-1, random_state=42, tree_method='hist')
    m_30d.fit(train_30d_clean[features], train_30d_clean['target_fwd_30d'])
    p_30d = pd.Series(m_30d.predict(cand_df[features]), index=cand_df['ticker']).nlargest(min(50, len(cand_df)))
    sc_30d = p_30d.clip(lower=0.0001)
    w_prop_30d = (sc_30d / sc_30d.sum()).values
    idx_30d = [prices_pivot.columns.get_loc(s) for s in p_30d.index if s in prices_pivot.columns]
    # T+1 Execution Lag
    w_purged_30_30[t_idx+1:end_idx, idx_30d] = w_prop_30d[:len(idx_30d)]

print(f"✅ 30-Day Cycles completed in {time.perf_counter() - t0_loop30:.2f}s!")

# -----------------------------------------------------------------------------
# 2. 15-DAY REBALANCE CYCLES (1981–2026: ~760 Cycles / Strict Trading-Bar Purge + T+1 Lag)
# -----------------------------------------------------------------------------
F15 = 15
rebal_dates_15 = [d for d in all_dates[::F15] if d >= burnin_end_date]
print(f"🚀 Running Half-Century Strict Trading-Days Purged 15-Day Walk-Forward ({len(rebal_dates_15)} cycles across 45.6 years)...")

t0_loop15 = time.perf_counter()

for c_idx, reb_date in enumerate(tqdm(rebal_dates_15, desc="15-Day Cycles")):
    t_idx = all_dates.get_loc(reb_date)
    end_idx = min(t_idx + 1 + F15, n_days)
    
    cand_df = df_master[(df_master['date'] == reb_date) & df_master['close'].notnull()]
    active_tickers = cand_df['ticker'].tolist()
    if len(active_tickers) == 0:
        continue
        
    # Strict Purge for 15-Day Model (Cutoff at least 15 trading bars prior to t_idx)
    purge_idx_15 = max(0, t_idx - 15)
    train_15d = df_master[df_master['date'] <= all_dates[purge_idx_15]].tail(100000)
    train_15d_clean = train_15d[train_15d['target_fwd_15d'].notnull()]
    
    m_15d = xgb.XGBRegressor(n_estimators=40, max_depth=4, learning_rate=0.05, n_jobs=-1, random_state=42, tree_method='hist')
    m_15d.fit(train_15d_clean[features], train_15d_clean['target_fwd_15d'])
    p_15d = pd.Series(m_15d.predict(cand_df[features]), index=cand_df['ticker']).nlargest(min(50, len(cand_df)))
    sc_15d = p_15d.clip(lower=0.0001)
    w_prop_15d = (sc_15d / sc_15d.sum()).values
    idx_15d = [prices_pivot.columns.get_loc(s) for s in p_15d.index if s in prices_pivot.columns]
    # T+1 Execution Lag
    w_purged_15_15[t_idx+1:end_idx, idx_15d] = w_prop_15d[:len(idx_15d)]

print(f"✅ 15-Day Cycles completed in {time.perf_counter() - t0_loop15:.2f}s!")

🚀 Running Half-Century Strict Trading-Days Purged 30-Day Walk-Forward (371 cycles across 45.6 years)...

30-Day Cycles:   0%|          | 0/371 [00:00<?, ?it/s]

✅ 30-Day Cycles completed in 309.23s!
🚀 Running Half-Century Strict Trading-Days Purged 15-Day Walk-Forward (767 cycles across 45.6 years)...

15-Day Cycles:   0%|          | 0/767 [00:00<?, ?it/s]

✅ 15-Day Cycles completed in 258.90s!

## 4. Half-Century Performance Analytics & Alpha Decomposition (1981–2026)

In [4]:
eval_mask = (all_dates >= burnin_end_date)
eval_dates = all_dates[eval_mask]
eval_start_idx = all_dates.get_loc(burnin_end_date)

curves = {
    '1. S&P 500 Index (^GSPC Benchmark)': (spx_aligned.loc[eval_dates] / spx_aligned.loc[eval_dates].iloc[0]) * 100.0,
    '2. Point-in-Time Active Universe B&H (No Lookahead)': pd.Series(np.cumprod(1.0 + np.sum(daily_rets_mat[eval_start_idx:] * w_active_bh[eval_start_idx:], axis=1)) * 100.0, index=eval_dates),
    '3. Institutional Purged XGBoost (30d Rebal, 5d Fwd, Equal Weight, T+1 Lag)': pd.Series(np.cumprod(1.0 + np.sum(daily_rets_mat[eval_start_idx:] * w_purged_30_5[eval_start_idx:], axis=1)) * 100.0, index=eval_dates),
    '4. Institutional Purged XGBoost (30d Rebal, 30d Fwd, Forecast Sizing, T+1 Lag)': pd.Series(np.cumprod(1.0 + np.sum(daily_rets_mat[eval_start_idx:] * w_purged_30_30[eval_start_idx:], axis=1)) * 100.0, index=eval_dates),
    '5. Institutional Purged XGBoost (15d Rebal, 15d Fwd, Forecast Sizing, T+1 Lag)': pd.Series(np.cumprod(1.0 + np.sum(daily_rets_mat[eval_start_idx:] * w_purged_15_15[eval_start_idx:], axis=1)) * 100.0, index=eval_dates)
}

df_master_curves = pd.DataFrame(curves, index=eval_dates).reset_index().rename(columns={'index': 'date'})

def compute_analytics(series, spx_series, rf=0.03):
    r_strat = series.pct_change().dropna()
    r_spx = spx_series.pct_change().dropna()
    aligned = pd.concat([r_strat, r_spx], axis=1).dropna()
    r_strat, r_spx = aligned.iloc[:, 0], aligned.iloc[:, 1]
    
    n_years = len(r_strat) / 252.0
    total_ret = (series.iloc[-1] / series.iloc[0]) - 1.0
    cagr = (series.iloc[-1] / series.iloc[0]) ** (1.0 / max(n_years, 0.1)) - 1.0
    ann_excess = (r_strat.mean() * 252.0) - rf
    ann_vol = r_strat.std() * np.sqrt(252.0)
    sharpe = ann_excess / ann_vol if ann_vol > 0 else 0.0
    downside_vol = r_strat[r_strat < 0].std() * np.sqrt(252.0)
    sortino = ann_excess / downside_vol if downside_vol > 0 else 0.0
    
    drawdown = (series - series.cummax()) / series.cummax()
    max_dd = drawdown.min()
    calmar = cagr / abs(max_dd) if abs(max_dd) > 0 else 0.0
    
    cov_matrix = np.cov(r_strat, r_spx)
    beta = cov_matrix[0, 1] / cov_matrix[1, 1] if cov_matrix[1, 1] > 0 else 1.0
    spx_cagr = (spx_series.iloc[-1] / spx_series.iloc[0]) ** (1.0 / max(n_years, 0.1)) - 1.0
    alpha = (cagr - rf) - beta * (spx_cagr - rf)
    
    return {
        'Total Return (%)': total_ret * 100.0,
        'CAGR (%)': cagr * 100.0,
        'Sharpe Ratio': sharpe,
        'Sortino Ratio': sortino,
        'Max Drawdown (%)': max_dd * 100.0,
        'Calmar Ratio': calmar,
        'Market Beta (β)': beta,
        'Jensen Alpha (α %)': alpha * 100.0
    }

analytics_records = []
for name, s in curves.items():
    analytics_records.append({'Strategy / Model': name, **compute_analytics(s, curves['1. S&P 500 Index (^GSPC Benchmark)'])})

df_performance_table = pd.DataFrame(analytics_records)
print("=== HALF-CENTURY (1981–2026) INSTITUTIONAL ZERO-LEAKAGE PERFORMANCE & RISK MATRIX ===")
df_performance_table

=== HALF-CENTURY (1981–2026) INSTITUTIONAL ZERO-LEAKAGE PERFORMANCE & RISK MATRIX ===

,Strategy / Model,Total Return (%),CAGR (%),Sharpe Ratio,Sortino Ratio,Max Drawdown (%),Calmar Ratio,Market Beta (β),Jensen Alpha (α %)
0,1. S&P 500 Index (^GSPC Benchmark),5529.822797,9.230016,0.416663,0.523635,-56.775388,0.162571,1.000000,0.000000
1,2. Point-in-Time Active Universe B&H (No Looka...,299723.343807,19.166886,0.908929,1.166969,-45.710596,0.419309,0.962668,10.169452
2,"3. Institutional Purged XGBoost (30d Rebal, 5d...",321974.437742,19.353893,0.913948,1.174608,-46.667712,0.414717,0.966206,10.334414
3,"4. Institutional Purged XGBoost (30d Rebal, 30...",859228.239665,21.947228,0.949775,1.235391,-41.150268,0.533344,1.044514,12.439890
4,"5. Institutional Purged XGBoost (15d Rebal, 15...",934181.004564,22.170805,0.940472,1.223979,-47.055399,0.471164,1.064216,12.540724

## 5. Interactive Half-Century Visualizer (Log Scale: 1981–2026) & Drawdowns

In [5]:
fig = make_subplots(rows=2, cols=1, shared_xaxes=True, vertical_spacing=0.08,
                    subplot_titles=('<b>Half-Century Zero-Leakage Walk-Forward Equity Curves (Log Scale: 1981–2026)</b>',
                                    '<b>Underwater Drawdown Curves (%)</b>'))

palette = [
    '#636EFA',  # 1. SP500
    '#FFA15A',  # 2. Active Universe B&H
    '#AB63FA',  # 3. Purged 30_5
    '#00CC96',  # 4. Purged 30_30 (Hero 1)
    '#FFDF00'   # 5. Purged 15_15 (Hero 2)
]

for idx, (name, s) in enumerate(curves.items()):
    c = palette[idx % len(palette)]
    is_hero = ('4.' in name or '5.' in name)
    fig.add_trace(go.Scatter(
        x=df_master_curves['date'], y=s, name=name,
        line=dict(color=c, width=3.0 if is_hero else 1.8)
    ), row=1, col=1)
    
    dd = ((s - s.cummax()) / s.cummax()) * 100.0
    fig.add_trace(go.Scatter(
        x=df_master_curves['date'], y=dd, name=f"{name} DD", showlegend=False,
        line=dict(color=c, width=1.5)
    ), row=2, col=1)

fig.update_yaxes(type="log", row=1, col=1, title="<b>Portfolio Value ($ Log Scale)</b>")
fig.update_yaxes(row=2, col=1, title="<b>Drawdown (%)</b>")

fig.update_layout(
    template='plotly_dark', width=1200, height=850,
    title='<b>Half-Century Zero-Leakage Benchmark (1981–2026): Trading-Bar Purge + T+1 Lag + Active Universe</b>',
    margin=dict(l=60, r=320, t=80, b=60),
    legend=dict(orientation='v', yanchor='top', y=1.0, xanchor='left', x=1.02, title=dict(text='<b>Strategy / Model</b>'))
)
fig.show()

## 6. Decade-by-Decade Quantitative Breakdown (1981–2026)

In [6]:
decades = [
    ('1980s (1981–1989)', pd.to_datetime('1981-01-02'), pd.to_datetime('1989-12-29')),
    ('1990s (1990–1999)', pd.to_datetime('1990-01-02'), pd.to_datetime('1999-12-31')),
    ('2000s (2000–2009)', pd.to_datetime('2000-01-03'), pd.to_datetime('2009-12-31')),
    ('2010s (2010–2019)', pd.to_datetime('2010-01-04'), pd.to_datetime('2019-12-31')),
    ('2020s (2020–2026)', pd.to_datetime('2020-01-02'), pd.to_datetime('2026-08-27'))
]

decade_records = []
for dec_name, d_start, d_end in decades:
    row = {'Decade / Market Era': dec_name}
    for name, s in curves.items():
        s_sub = s[(s.index >= d_start) & (s.index <= d_end)]
        if len(s_sub) > 0:
            sub_ret = (s_sub.iloc[-1] / s_sub.iloc[0] - 1.0) * 100.0
            row[name.split('.')[1].strip().split('(')[0].strip()] = round(sub_ret, 2)
    decade_records.append(row)

df_decades = pd.DataFrame(decade_records)
print("=== DECADE-BY-DECADE TOTAL RETURN BREAKDOWN (%) ===")
df_decades

=== DECADE-BY-DECADE TOTAL RETURN BREAKDOWN (%) ===

,Decade / Market Era,S&P 500 Index,Point-in-Time Active Universe B&H,Institutional Purged XGBoost
0,1980s (1981–1989),159.20,557.57,739.63
1,1990s (1990–1999),308.48,1305.76,1791.85
2,2000s (2000–2009),-23.37,153.53,271.04
3,2010s (2010–2019),185.16,341.40,353.74
4,2020s (2020–2026),135.61,180.49,232.63

## 7. Export Half-Century Zero-Leakage Simulation to Excel

In [7]:
out_path = os.path.join(LOCAL_DATA_DIR, "half_century_institutional_zero_leakage_walkforward_simulation_poc.xlsx")
with pd.ExcelWriter(out_path) as writer:
    df_master_curves.to_excel(writer, sheet_name='daily_equity_curves', index=False)
    df_performance_table.to_excel(writer, sheet_name='performance_summary', index=False)
    df_decades.to_excel(writer, sheet_name='decade_breakdown', index=False)

print(f"💾 Successfully exported Half-Century Zero-Leakage Benchmark to: {out_path}")

💾 Successfully exported Half-Century Zero-Leakage Benchmark to: c:\Users\honza\Desktop\projects\stock-analysis\research\notebooks\algo-alpha-execution\data\fetched\half_century_institutional_zero_leakage_walkforward_simulation_poc.xlsx